[FEAT] create home screen UI
Kyonggi-Univ-Diet-Information/FE pull request #8
Opened 2024-09-29 14:00 UTC by boroboro01

## #️⃣연관된 이슈

> #1 

## 📝작업 내용

- add fonts(BMHANNAPro, Pretendard)

### home page UI
- create menu-card component(with transition)
- create today-title content
- create carousel control button
- create floating action button

![splasfshdd-2](https://github.com/user-attachments/assets/0d3a2c26-446d-4aa4-9021-ed1555ad1797)

## 💬리뷰 요구사항(선택)

> 홈 화면을 구성하는 기본 UI를 모두 만들었습니다
메뉴 카드를 제외한 부분은 재활용이 힘들어 홈 화면에 그대로 구성하셨습니다
Container내부에 Wrapper가 겹쳐있는데 조금 복잡해진 것 같습니다. 혹시 더 좋은 방법이 있다면 알려주세요!
+반응형은 다음 작업에서 추가하겠습니다!

2024-09-29 14:27 UTC, cho4u4o requested changes

2024-09-29 14:27 UTC, cho4u4o commented on src/components/MenuCard.tsx
전체적으로 네이밍, 더미 데이터 구현까지 map 사용하여 깔끔합니다👏👍

2024-09-29 14:27 UTC, cho4u4o commented on src/pages/Home.tsx
`TodayTitleContainer`와 `TodayTitleWrapper`, 그리고 `ButtonWrapper`와 `ButtonContainer` 와 같이 내부에 가지고 있는 요소가 동일한 요소들은 하나로 합쳐 css를 적용하면 더 깔끔한 코드가 될 것 같습니다!!
또한 `TitleWrapper`와 같은 요소들은 위에서 따로 `TitleWrapper` 내에 필요 요소들을 넣어 정의, 필요 시 이름 수정 뒤 return에서는 title들을 가지고 있는 하나의 요소를 리턴해주면 더욱 깔끔한 코드가 될 것 같습니다!
즉 가독성을 위해 내부에서 component를 정의해 사용할 수도 있다는 것이 제 의견입니다! 🎯

2024-09-30 03:34 UTC, boroboro01 commented on src/pages/Home.tsx
좋은 방법이네요! Wrapper 코드의 일부를 Conatiner와 통합하고 전체를 감싸는 Content를 사용하여 리팩토링 했습니다! TitleWrapper에 관해서는 화요일에 한 번 자세히 이야기 해주세요!

2024-09-30 04:28 UTC, cho4u4o commented on src/pages/Home.tsx
전보다 훨씬 깔끔해졌네요! 좋습니다😁

2024-09-30 04:28 UTC, cho4u4o approved these changes

2024-09-30 04:29 UTC, merged